<?php

use Illuminate\Database\Seeder;

class HrwChecklistsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('hrw_checklists')->insert([
            [ 'id'=>1,'hrw_id'=>'1','seq_no'=>'1','description'=>'Cable and other M&E underground services detection has been carried out and approval obtained from relevant authorities if required for termination or diversion of supply.'],
            [ 'id'=>2,'hrw_id'=>'1','seq_no'=>'2','description'=>'Water, Electricity and Gas supplies are terminated'],
            [ 'id'=>3,'hrw_id'=>'1','seq_no'=>'3','description'=>'The method of demolition has been prepared and based on the systematic removal of structural elements to ensure the structural stability of adjacent structure'],
            [ 'id'=>4,'hrw_id'=>'1','seq_no'=>'4','description'=>'The shoring and method of demolition is in accordance with P.E design / procedures'],
            [ 'id'=>5,'hrw_id'=>'1','seq_no'=>'5','description'=>'To provide and ensure buffer zones are adequately barricaded and warning signs put up at conspicuous positions '],
            [ 'id'=>6,'hrw_id'=>'1','seq_no'=>'6','description'=>'Ensure safe means of access throughout the demolition work'],
            [ 'id'=>7,'hrw_id'=>'1','seq_no'=>'7','description'=>'Ensure no person is permitted to enter any demolition area unless all necessary protective measures are provided.'],
            [ 'id'=>8,'hrw_id'=>'1','seq_no'=>'8','description'=>'Ensure all uncollapsed structures are safe before any worker is allowed to enter for work'],
            [ 'id'=>9,'hrw_id'=>'2','seq_no'=>'1','description'=>'Required safety and rescue equipment as well as suitable reviving apparatus must be checked to be in good working condition'],
            [ 'id'=>10,'hrw_id'=>'2','seq_no'=>'2','description'=>'Adequate and appropriate personal protective equipment must be worn/used.'],
            [ 'id'=>11,'hrw_id'=>'2','seq_no'=>'3','description'=>'A confined space attendant, trained in emergency first-air (CPR), must be in attendance adjacent to the entrance of the confined space.'],
            [ 'id'=>12,'hrw_id'=>'2','seq_no'=>'4','description'=>'Name and identification badge of persons entering a confined space must be displayed at the entrance of the confined space.'],
            [ 'id'=>13,'hrw_id'=>'2','seq_no'=>'5','description'=>'De-energization/lockout-tagout (LOTO) carried out.'],
            [ 'id'=>14,'hrw_id'=>'2','seq_no'=>'6','description'=>'Blanking/bleeding of pipes.'],
            [ 'id'=>15,'hrw_id'=>'2','seq_no'=>'7','description'=>'Excess water must be removed'],
            [ 'id'=>16,'hrw_id'=>'2','seq_no'=>'8','description'=>'Barriers must be placed around openings.'],
            [ 'id'=>17,'hrw_id'=>'2','seq_no'=>'9','description'=>'If there is more than one entrance, at least two entrances must be opened for ventilation.'],
            [ 'id'=>18,'hrw_id'=>'2','seq_no'=>'10','description'=>'Lighting must be adequate.'],
            [ 'id'=>19,'hrw_id'=>'2','seq_no'=>'11','description'=>'The atmosphere of the confined space must be tested with a multi-gas monitor for oxygen deficiency, flammable/explosive gases and toxic/contaminant gases, determined as safe and the results recorded below by a Confined Space Safety Assessor. If 2 or more persons are present in the confined space, at least one of them continuously monitors the atmosphere with a suitable gas detector.'],
            [ 'id'=>20,'hrw_id'=>'2','seq_no'=>'12','description'=>'The atmosphere must be continuously monitored while the space is occupied (Atmospheric test results to be entered into record on page 3 of 3.'],
            [ 'id'=>21,'hrw_id'=>'2','seq_no'=>'13','description'=>'Any fan and pump must be turned on and working.'],
            [ 'id'=>22,'hrw_id'=>'2','seq_no'=>'14','description'=>'All working personnel must be warned of the hazards and the risks and the means to minimize or, where possible, eliminate the risks'],
            [ 'id'=>23,'hrw_id'=>'2','seq_no'=>'15','description'=>'All working personnel must be briefed on the safe work procedures including emergency escape & rescue procedures and sign this Permit before work starts.'],
            [ 'id'=>24,'hrw_id'=>'2','seq_no'=>'16','description'=>'All working personnel had attended and passed the SIC (Manhole) for Supervisors or SOC (Manhole) for workers as the case may be, where applicable (relevant certificates to be attached).'],
            [ 'id'=>25,'hrw_id'=>'2','seq_no'=>'17','description'=>'If hot work is to be carried out, attach Hot Work permit and ensure all hot work procedures are followed.'],
            [ 'id'=>26,'hrw_id'=>'3','seq_no'=>'1','description'=>'Cables and other M&E underground services detection has been carried out and approval obtained from relevant authorities if required'],
            [ 'id'=>27,'hrw_id'=>'3','seq_no'=>'2','description'=>'Trained and certified excavator operator.'],
            [ 'id'=>28,'hrw_id'=>'3','seq_no'=>'3','description'=>'Depth of excavation> 1.5m but less than 4m, adequate shoring shall be provided to prevent collapse of the excavation'],
            [ 'id'=>29,'hrw_id'=>'3','seq_no'=>'4','description'=>'Depth of excavation>1.5m but less than 4m, has been examined and certified by a PE to be safe without shoring'],
            [ 'id'=>30,'hrw_id'=>'3','seq_no'=>'5','description'=>'Depth of excavation>4m but less than 6m, the shoring is to be constructed in accordance to PE design and a COS issued before other work can start'],
            [ 'id'=>31,'hrw_id'=>'3','seq_no'=>'6','description'=>'Depth of excavation>6m requires PE & PE (GEO) design and supervision – refer to separate document'],
            [ 'id'=>32,'hrw_id'=>'3','seq_no'=>'7','description'=>'Material including excavated earth and other superimposed loads are piled/placed at a safe distance away from the edge'],
            [ 'id'=>33,'hrw_id'=>'3','seq_no'=>'8','description'=>'To provide and ensure open sides of excavation  than 2m depth are guarded by adequate barricades and warning sign put up at conspicuous positions'],
            [ 'id'=>34,'hrw_id'=>'3','seq_no'=>'9','description'=>'Ensure no person is permitted to enter any excavated area unless all necessary protective measures are provided.'],
            [ 'id'=>35,'hrw_id'=>'3','seq_no'=>'10','description'=>'Ensure water is pumped out before any worker is allowed to work in the trench/pit.'],
            [ 'id'=>36,'hrw_id'=>'3','seq_no'=>'11','description'=>'Ensure provision of life lines for working in excavation/trench while installing strut between shoring'],
            [ 'id'=>37,'hrw_id'=>'3','seq_no'=>'12','description'=>'Ensure timber planks used for shoring are 50mm thick/in accordance with PE design'],
            [ 'id'=>38,'hrw_id'=>'3','seq_no'=>'13','description'=>'Ensure shoring materials are not defective and are of adequate strength'],
            [ 'id'=>39,'hrw_id'=>'3','seq_no'=>'14','description'=>'Provide ladder or other safe means of ingress/egress for excavation more than 1.2m depth.'],
            [ 'id'=>40,'hrw_id'=>'3','seq_no'=>'15','description'=>'Ensure to check and monitor the banks and soil condition regularly especially after heavy downpour'],
            [ 'id'=>41,'hrw_id'=>'4','seq_no'=>'1','description'=>'Flame or spark-producing equipment to be used has been inspected and found in good condition.'],
            [ 'id'=>42,'hrw_id'=>'4','seq_no'=>'2','description'=>'There are no combustible fibres, dusts , vapors, gases or liquids in the area.'],
            [ 'id'=>43,'hrw_id'=>'4','seq_no'=>'3','description'=>'The absence of flammable gases or vapors has been verified by a combustible gas detection instrument.'],
            [ 'id'=>44,'hrw_id'=>'4','seq_no'=>'4','description'=>'Flashback arrestors fitted to gas cylinders and torch inlet.'],
            [ 'id'=>45,'hrw_id'=>'4','seq_no'=>'5','description'=>'Two-ear clamps (not jubilee clips) used for hose connection'],
            [ 'id'=>46,'hrw_id'=>'4','seq_no'=>'6','description'=>'Gas cylinders secured in an upright position and placed at safe distance from burner / torch'],
            [ 'id'=>47,'hrw_id'=>'4','seq_no'=>'7','description'=>'Appropriate fire extinguishers are located at the working area.'],
            [ 'id'=>48,'hrw_id'=>'4','seq_no'=>'8','description'=>'The work will be confined to the area or equipment specified on this permit'],
            [ 'id'=>49,'hrw_id'=>'4','seq_no'=>'9','description'=>'Surrounding area has been swept clean and , if combustible, we down or otherwise protected'],
            [ 'id'=>50,'hrw_id'=>'4','seq_no'=>'10','description'=>'Contractor has ample portable fire extinguishers available and trained personnel to use them'],
            [ 'id'=>51,'hrw_id'=>'4','seq_no'=>'11','description'=>'All combustibles have been relocated 15m away from the operation and the remainder protected with metal guards or flame-proofed curtains or covers(not ordinary tarpaulins)'],
            [ 'id'=>52,'hrw_id'=>'4','seq_no'=>'12','description'=>'Responsible personnel have been assigned to provide a “Fire Watch” for dangerous sparks in the work area, as well as on floors above and below while work is being performed'],
            [ 'id'=>53,'hrw_id'=>'4','seq_no'=>'13','description'=>'If operating adjacent to gas supply, turn off supply or protect the pipe.'],
            [ 'id'=>54,'hrw_id'=>'4','seq_no'=>'14','description'=>'Check area 1 hour after the hot work ended.'],
            [ 'id'=>55,'hrw_id'=>'5','seq_no'=>'1','description'=>'Authorized Examiner inspected & certified the crane and lifting gears'],
            [ 'id'=>56,'hrw_id'=>'5','seq_no'=>'2','description'=>'Only registered Crane Operators are allowed to operate the crane.'],
            [ 'id'=>57,'hrw_id'=>'5','seq_no'=>'3','description'=>'Certified Lifting Supervisor has been appointed to supervise the lifting operation.'],
            [ 'id'=>58,'hrw_id'=>'5','seq_no'=>'4','description'=>'Certified signalmen and riggers are appointed for the lifting operation.'],
            [ 'id'=>59,'hrw_id'=>'5','seq_no'=>'5','description'=>'The lifting gears (slings, shackles, etc) are checked for signs of physical defects.'],
            [ 'id'=>60,'hrw_id'=>'5','seq_no'=>'6','description'=>'Automatic overload cut-off devices are in good working condition.'],
            [ 'id'=>61,'hrw_id'=>'5','seq_no'=>'7','description'=>'The Crane Operator and Lifting Supervisors are aware of the safe working load of the crane.'],
            [ 'id'=>62,'hrw_id'=>'5','seq_no'=>'8','description'=>'The founding platform/parking area of the crane is stable for the lifting operations.'],
            [ 'id'=>63,'hrw_id'=>'5','seq_no'=>'9','description'=>'The foundation of the crane has been designed by P.E. and constructed in accordance with design.'],
            [ 'id'=>64,'hrw_id'=>'5','seq_no'=>'10','description'=>'The founding platform has been certified by the P.E.'],
            [ 'id'=>65,'hrw_id'=>'5','seq_no'=>'11','description'=>'Provide and maintain safe access for mobile and crawler cranes.'],
            [ 'id'=>66,'hrw_id'=>'5','seq_no'=>'12','description'=>'Ensure that outriggers are fully extended on solid ground/steel plate.'],
            [ 'id'=>67,'hrw_id'=>'5','seq_no'=>'13','description'=>'Lifting area/zone effectively cordoned off with warning signs prominently displayed.'],
            [ 'id'=>68,'hrw_id'=>'5','seq_no'=>'14','description'=>'Hazard of lifting operations have been identified, risk control measures implemented and communicated to all involved.'],
            [ 'id'=>69,'hrw_id'=>'6','seq_no'=>'1','description'=>'Authorized Examiner inspected & certified the excavator and lifting gears'],
            [ 'id'=>70,'hrw_id'=>'6','seq_no'=>'2','description'=>'Only registered Excavator Operators are allowed to operate the excavator.'],
            [ 'id'=>71,'hrw_id'=>'6','seq_no'=>'3','description'=>'Certified Lifting Supervisor has been appointed to supervise the lifting operation.'],
            [ 'id'=>72,'hrw_id'=>'6','seq_no'=>'4','description'=>'Certified signalmen and riggers are appointed for the lifting operation.'],
            [ 'id'=>73,'hrw_id'=>'6','seq_no'=>'5','description'=>'The lifting gears (slings, shackles, etc) are checked for signs of physical defects.'],
            [ 'id'=>74,'hrw_id'=>'6','seq_no'=>'6','description'=>'Automatic overload cut-off devices are in good working condition.'],
            [ 'id'=>75,'hrw_id'=>'6','seq_no'=>'7','description'=>'The Excavator Operator and Lifting Supervisors are aware of the safe working load of the crane.'],
            [ 'id'=>76,'hrw_id'=>'6','seq_no'=>'8','description'=>'Provide and maintain safe access for excavator.'],
            [ 'id'=>77,'hrw_id'=>'6','seq_no'=>'9','description'=>'Lifting area/zone effectively cordoned off with warning signs prominently displayed.'],
            [ 'id'=>78,'hrw_id'=>'6','seq_no'=>'10','description'=>'Hazard of lifting operations have been identified, risk control measures implemented and communicated to all involved.'],
            [ 'id'=>79,'hrw_id'=>'7','seq_no'=>'1','description'=>'The piling machinery has been inspected by an authorized examiner'],
            [ 'id'=>80,'hrw_id'=>'7','seq_no'=>'2','description'=>'The piling operators are trained and authorized'],
            [ 'id'=>81,'hrw_id'=>'7','seq_no'=>'3','description'=>'Piling machinery inspected by a designated competent person prior to the start of piling each day (Daily inspection record)'],
            [ 'id'=>82,'hrw_id'=>'7','seq_no'=>'4','description'=>'Precondition survey has been conducted'],
            [ 'id'=>83,'hrw_id'=>'7','seq_no'=>'5','description'=>'Underground services detection has been conducted'],
            [ 'id'=>84,'hrw_id'=>'7','seq_no'=>'6','description'=>'The safety hazards have been identified and all workers are warned'],
            [ 'id'=>85,'hrw_id'=>'7','seq_no'=>'7','description'=>'All lifting gears are in good working condition'],
            [ 'id'=>86,'hrw_id'=>'7','seq_no'=>'8','description'=>'Method of work and sequence of piling has been approved'],
            [ 'id'=>87,'hrw_id'=>'7','seq_no'=>'9','description'=>'Ground monitoring system has been installed and initial reading taken'],
            [ 'id'=>88,'hrw_id'=>'7','seq_no'=>'10','description'=>'Buffer zones for safety has been established'],
            [ 'id'=>89,'hrw_id'=>'7','seq_no'=>'11','description'=>'All hot work (welding / gas cutting work) to submit separate application for Hot Work Permit'],
            [ 'id'=>90,'hrw_id'=>'7','seq_no'=>'12','description'=>'Designated area for storage'],
            [ 'id'=>91,'hrw_id'=>'7','seq_no'=>'13','description'=>'Have considered the safety for vehicular movement within working areas'],
            [ 'id'=>92,'hrw_id'=>'7','seq_no'=>'14','description'=>'Appoint certified lifting supervisor, signalmen and riggers for lifting operations'],
            [ 'id'=>93,'hrw_id'=>'8','seq_no'=>'1','description'=>'All personnel are adequately trained to perform work at heights'],
            [ 'id'=>94,'hrw_id'=>'8','seq_no'=>'2','description'=>'Safe means of access or egress provided where scaffold/MEWP is used, respective checklist is/are attached.'],
            [ 'id'=>95,'hrw_id'=>'8','seq_no'=>'3','description'=>'Opening / open sides are barricaded unless free access is required for work in progress and reinstated thereafter.'],
            [ 'id'=>96,'hrw_id'=>'8','seq_no'=>'4','description'=>'Guardrail is used , top rail min 1m , distance between intermediate rails and gaps between vertical guards/structure  max 0.6m'],
            [ 'id'=>97,'hrw_id'=>'8','seq_no'=>'5','description'=>'Travel restraint system used to prevent persons from falling risks are in good condition'],
            [ 'id'=>98,'hrw_id'=>'8','seq_no'=>'6','description'=>'Fall Arrest System used to prevent vertical fall are in good condition and falling distance (Clearance height) is cleared.'],
            [ 'id'=>99,'hrw_id'=>'8','seq_no'=>'7','description'=>'Prominent warning notices are affixed for fragile surface'],
            [ 'id'=>100,'hrw_id'=>'8','seq_no'=>'8','description'=>'Safety hook must be anchored to life line or fixed structure at all times'],
            [ 'id'=>101,'hrw_id'=>'8','seq_no'=>'9','description'=>'Anchorage and anchorage lines are in order.'],
            [ 'id'=>102,'hrw_id'=>'8','seq_no'=>'10','description'=>'No of defective anchorage found & replaced'],
            [ 'id'=>103,'hrw_id'=>'8','seq_no'=>'11','description'=>'No of defective lifeline found & replaced.'],
            [ 'id'=>104,'hrw_id'=>'8','seq_no'=>'12','description'=>'All person subjected to falling risks are equipped with Personal  Fall prevention equipment (double lanyard harness)'],
            [ 'id'=>105,'hrw_id'=>'8','seq_no'=>'13','description'=>'Hazards and risk assessments are conducted and communicated.'],
                
        ]);
    }
}
